name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Print Greeting" |
          echo "Hello World!"
      - name: Print Farewell
        run: echo "Print Farewell" |
          echo "Goodbye World!"
